name: Rust Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "crates/**"
      - "examples/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/rust_test.yml"
  pull_request:
    branches:
      - main
    paths:
      - "crates/**"
      - "examples/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/rust_test.yml"

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test Debug - x86_64
            runner: ubuntu-latest
            command: rust-test
            needs-sccache: true
          - name: Test Release - x86_64
            runner: ubuntu-latest
            command: rust-test-release
            needs-sccache: true
          - name: Test Debug - aarch64
            runner: ubuntu-24.04-arm
            command: rust-test
            needs-sccache: true

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-rust-cache
        with:
          with-sccache: ${{ matrix.needs-sccache }}

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.0
          cache: true

      - name: Run ${{ matrix.command }}
        run: pixi run ${{ matrix.command }}

      - name: Show sccache stats
        if: matrix.needs-sccache
        run: sccache --show-stats
        continue-on-error: true

      - name: Post job cleanup
        if: matrix.needs-sccache
        run: sccache --stop-server || true
        continue-on-error: true
